version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build-front:
    docker:
      - image: 'circleci/node:erbium'
    steps:
      - checkout
      - run: 
          name: Copy env and client build for staging
          command: |
            cd client && npm install && cp env-cmdrc .envcmdrc && npm build:staging
  deploy-front-s3:
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          overwrite: true
          to: "s3://ms.codingtree.pl"


workflows:
  build-and-deploy-staging:
    jobs:
      - build-front
      - deploy-front-s3:
          requires:
            - build-front # only deploy once build job has completed
          filters:
            branches:
              only: develop # only deploy on the develop branch